//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApniShopWebAssignment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoginRegisterDatabaseEntities2 : DbContext
    {
        public LoginRegisterDatabaseEntities2()
            : base("name=LoginRegisterDatabaseEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OTable> OTables { get; set; }
        public virtual DbSet<PTable> PTables { get; set; }
        public virtual DbSet<UPTable> UPTables { get; set; }
        public virtual DbSet<UTable> UTables { get; set; }
    }
}
