//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApniShopWebAssignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    public partial class PTable
    {
        public int PID { get; set; }
        public string PName { get; set; }
        public string PImage { get; set; }
        public string PCategory { get; set; }
        public Nullable<int> PRating { get; set; }
        public Nullable<double> PPrice { get; set; }
        public Nullable<int> PWish { get; set; }
        public Nullable<int> PQuantity { get; set; }
        public Nullable<int> popularity { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
