//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApniShopWebAssignment.Models
{
    using System;
    using System.Web;
    using System.Collections.Generic;
    
    public partial class UTable
    {
        public int UID { get; set; }
        public string Uname { get; set; }
        public string UPassword { get; set; }
        public Nullable<bool> UIsAdmin { get; set; }
        public string UGender { get; set; }
        public string UBirthday { get; set; }
        public string UAddress { get; set; }
        public string UProfilePicturePath { get; set; }
        public string UMobileNo { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }

    }
}
